#!/bin/sh
### BEGIN INIT INFO
# Provides: install_ergo
# Required-Start:
# Required-Stop:

do_start
{
PASSWORD="a_password"
UNIT_ID="a_id" 

#sets up apt sources
wget -O -  http://packages.ergotelescope.org/ergo.gpg.key | apt-key add - 

#sets up ergo and unattended-upgrades
apt-get update
apt-get upgrade -y
apt-get install -y ergo-telescope unattended-upgrades apt-listchanges;
apt-get update

#changes the password for the unit with the format password unit_id 
# eg password555
echo -e "$PASSWORD$UNIT_ID\n$PASSWORD$UNIT_ID" |(passwd pi)
echo "$UNIT_ID" > /etc/ERGO/unit_id

#adds a key for admins. 
mkdir -p /home/pi/.ssh
cat /root/master_key >> /home/pi/.ssh/authorized_keys

chmod 600 /etc/init.d/install_ergo
update-rc.d install_ergo remove
}
