#!/bin/sh
### BEGIN INIT INFO
# Provides: install_ergo
# Required-Start:
# Required-Stop:
# Default-Start: 2 
# Default-Stop:
# Short-Description: Calls the install ergo script when there is internet 
# Description:
### END INIT INFO

do_start()
{
bash /usr/lib/raspi-config/install_ergo.sh &
}

do_start

