#!/bin/sh
### BEGIN INIT INFO
# Provides: install_ergo
# Required-Start:
# Required-Stop:
# Default-Start: 2 
# Default-Stop:
# Short-Description: Calls the install ergo script when there is internet 
# Description:
### END INIT INFO

do_start()
{
while ! ping -q -c 1 -W 1 8.8.8.8 > /dev/null ; do
	sleep 10	
done
bash /usr/lib/raspi-config/install_ergo.sh &
}

do_start

